// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
import HomeChartsController from "./home_charts_controller"
import LucideController from "./lucide_controller"
import ImportacaoUploadController from "./importacao_upload_controller"
import OperacaoItensController from "./operacao_itens_controller"
import PedidoItensController from "./pedido_itens_controller"
import FlashController from "./flash_controller"
import ProdutosController from "./produtos_controller"

application.register("hello", HelloController)
application.register("home-charts", HomeChartsController)
application.register("lucide", LucideController)
application.register("importacao-upload", ImportacaoUploadController)
application.register("operacao-itens", OperacaoItensController)
application.register("pedido-itens", PedidoItensController)
application.register("flash", FlashController)
application.register("produtos", ProdutosController)






