// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
import HomeChartsController from "./home_charts_controller"
import LucideController from "./lucide_controller"

application.register("hello", HelloController)
application.register("home-charts", HomeChartsController)
application.register("lucide", LucideController)








